### ISSUE TITLE
Forward plugin.

### ISSUE THREAD

**Issue by DreamVoid** [Oharass/FreedomChat#13]
Can I forward this plugin to [MCBBS](https://www.mcbbs.net) (a Chinese Minecraft Community)? I believe Chinese players will like your plugin. I'll introduce in Chinese, and I'll state your authorship and link to GitHub and Modrinth.

**Comment by DreamVoid** [comment]
> Go ahead. Just please link to Modtinth for downloads. Do not reupload jars there if possible.

Thank you. (●'◡'●)

**Comment by MIOGMIOG** [comment]
[https://www.mcbbs.net/thread-1380868-1-1.html](https://www.mcbbs.net/thread-1380868-1-1.html)
Found the page
