### ISSUE TITLE
1.0.1 issue

### ISSUE THREAD

**Issue by TwilightGamerPro** [Oharass/FreedomChat#4]
![image](https://user-images.githubusercontent.com/21987543/181863236-2d2bc904-09ba-4a5e-9b49-abe4bf01aa60.png)

This is upon joining using 1.19.1 client

Here is the error message via text wise:
`TwilightGamerPro lost connection: Internal Exception: java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.ClientboundServerDataPacket.<init>(net.minecraft.network.chat.IChatBaseComponent, java.lang.String, boolean, boolean)'`

**Comment by TwilightGamerPro** [comment]
Correction may want to put a warning that the server has to be in 1.19.1 so that error does not show up!

**Comment by cobaltgit** [comment]
What version is your server running?

**Comment by cobaltgit** [comment]
You must be having a version mismatch, I don't have such an issue with FreedomChat 1.0.1 on both 1.19.1 client and server

**Comment by TwilightGamerPro** [comment]
> You must be having a version mismatch, I don't have such an issue with FreedomChat 1.0.1 on both 1.19.1 client and server

should of read 

> Correction may want to put a warning that the server has to be in 1.19.1 so that error does not show up!

as that is my correction to it.
