### ISSUE TITLE
Chat validation issue

### ISSUE THREAD

**Issue by wilderop** [Oharass/FreedomChat#5]
With this plugin installed, players are randomly kicked whenever they use chat (but not every time). Nothing shows up in console, but the player being disconnected with the message chat validation failure.

**Comment by Oharass** [comment]
which version are you using? have you downloaded from releases or built yourself?

**Comment by Oharass** [comment]
Fixed in release v1.1.0. I already fix this last week but I forget to publish release. ty for report.
