### ISSUE TITLE
Upload to SpigotMC

### ISSUE THREAD

**Issue by ssterling** [Oharass/FreedomChat#6]
Request: upload to the [SpigotMC plugin repository](https://www.spigotmc.org/resources/categories/spigot.4/).

There are tons of half-baked alternatives on there, so having something that works—that is, FreedomChat—would be quite nice.

**Comment by andrewkm** [comment]
Yes definitely @Oharass 
You got a lot of support behind this, reviews will come pouring in! Amazing work!

**Comment by Oharass** [comment]
I have uploaded to modrinth https://modrinth.com/mod/freedomchat (it is pending approval, it might take a few hrs). I do not like spigotmc very much... I also do not want to be required to maintain Spigot compatibility. Especially for issues like #7, this will be issue. In the future plugin might only work Paper+.

**Comment by andrewkm** [comment]
Paper is the was to go :)

**Comment by TNTUP** [comment]
Paper's Hangar plugin repository but iirc its not production ready :( (followup comment of andrewkm)
